### ISSUE TITLE
Append to .bashrc file

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/prework#7]
Just in case the user has a `.bashrc` file already we should instruct them to append to it instead of overwriting it. Change this line: 

```sh
echo 'alias gs="git status"' > ~/.bashrc
```
to
```sh
echo 'alias gs="git status"' >> ~/.bashrc
```
in the Book 1 _Getting Started_ chapters for Windows and Mac

**Comment by stevebrownlee** [comment]
Good point. I made the assumption that everyone is a n00b
